version: "3.5"

services:
    postgres:
        restart: unless-stopped
        image: postgres
        container_name: "data-pg-docker"
        ports:
            - 5432:5432
        networks:
            - postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: localdbpass
            POSTGRES_DB: data
        volumes:
            - postgres_data:/data/postgres
    #metabase:
    #    container_name: "data-metabase"
    #    restart: unless-stopped
    #    image: metabase/metabase
    #    ports:
    #        - 8083:3000
    #    networks:
    #        - postgres
    #    depends_on:
    #        - postgres
    #    environment:
    #        MB_DB_TYPE: postgres
    #        MB_DB_DBNAME: metabase
    #        MB_DB_PORT: 5432
    #        MB_DB_USER: postgres
    #        MB_DB_PASS: localdbpass
    #        MB_DB_HOST: postgres

networks:
  postgres:
    driver: bridge

volumes:
    postgres_data:
