version: "3.5"

services:
    postgres:
        restart: unless-stopped
        image: postgres
        container_name: "sqrt-data-postgres"
        ports:
            - 5432:5432
        networks:
            - postgres
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: data
        volumes:
            - postgres_data:/data/postgres
    metabase:
        container_name: "sqrt-data-metabase"
        restart: unless-stopped
        image: metabase/metabase
        ports:
            - 8083:3000
        networks:
            - postgres
        depends_on:
            - postgres
        environment:
            MB_DB_TYPE: postgres
            MB_DB_DBNAME: metabase
            MB_DB_PORT: 5432
            MB_DB_USER: ${POSTGRES_USER}
            MB_DB_PASS: ${POSTGRES_PASSWORD}
            MB_DB_HOST: postgres
            JAVA_OPTS: "-Dc3p0.maxPoolSize=5 "
    sqrt_data_orion:
        container_name: "sqrt-data-orion"
        build: .
        ports:
            - 127.0.0.1:4200:4200
        restart: unless-stopped
        networks:
            - postgres
        depends_on:
            - postgres
        command: prefect orion start
        environment:
            PREFECT_ORION_DATABASE_CONNECTION_URL: "postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/orion"
            PREFECT_ORION_API_HOST: 0.0.0.0

    sqrt_data_agent:
        container_name: "sqrt-data-agent"
        build: .
        restart: unless-stopped
        networks:
            - postgres
        depends_on:
            - postgres
        volumes:
            - type: bind
              source: ./config.service.toml
              target: /config.service.toml
            - type: bind
              source: ~/logs-sync-debug
              target: /root/logs-sync-debug
            - ./config.service.local.toml:/app/config.service.local.toml
        command: prefect agent start -q "main"
        environment:
            PREFECT_API_URL: 'http://sqrt_data_orion:4200/api/'

    backups:
        image: prodrigestivill/postgres-backup-local
        restart: always
        volumes:
            - ./backups:/backups
        networks:
            - postgres
        depends_on:
            - postgres
        environment:
            - POSTGRES_HOST=postgres
            - POSTGRES_DB=data,metabase,orion
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_EXTRA_OPTS=-Fc -Z9
            - SCHEDULE=@daily
            - BACKUP_KEEP_DAYS=7
            - BACKUP_KEEP_WEEKS=4
            - BACKUP_KEEP_MONTHS=2
            - BACKUP_SUFFIX=.dump
            - HEALTHCHECK_PORT=8080

networks:
    postgres:
        driver: bridge

volumes:
    postgres_data:
